env:
  DIRECTORY: .output
  PROJECT_NAME: taborg

name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Enable Corepack
        run: corepack enable

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install dependencies
        run: yarn install

      - name: Zip extensions
        run: |
          yarn run zip &&
          yarn run zip:firefox

      - name: Build CRX
        run: |
          yarn run crx pack .output/chrome-mv3 -o ${{ env.DIRECTORY }}/${{env.PROJECT_NAME}}-${{ steps.get_version.outputs.version }}.crx

      - name: Determine Release Parameters
        id: release_params
        run: |
          if [ "${{ steps.check_tag.outputs.exists }}" == "true" ]; then
            echo "tag_name=v${{ steps.get_version.outputs.version }}-pre-${{ github.sha }}" >> "$GITHUB_OUTPUT"
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
            echo "name=Pre-release v${{ steps.get_version.outputs.version }}-${{ github.sha }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag_name=v${{ steps.get_version.outputs.version }}" >> "$GITHUB_OUTPUT"
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
            echo "name=v${{ steps.get_version.outputs.version }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release_params.outputs.tag_name }}
          name: ${{ steps.release_params.outputs.name }}
          draft: false
          prerelease: ${{ steps.release_params.outputs.prerelease }}
          files: |
            ${{ env.DIRECTORY }}/${{env.PROJECT_NAME}}-${{ steps.get_version.outputs.version }}-chrome.zip
            ${{ env.DIRECTORY }}/${{env.PROJECT_NAME}}-${{ steps.get_version.outputs.version }}-firefox.zip
            ${{ env.DIRECTORY }}/${{env.PROJECT_NAME}}-${{ steps.get_version.outputs.version }}-sources.zip
            ${{ env.DIRECTORY }}/${{env.PROJECT_NAME}}-${{ steps.get_version.outputs.version }}.crx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
